### ISSUE TITLE
As a patron I want to know the name of the section a general reference appears in

### ISSUE THREAD

**Issue by dpriskorn** [internetarchive/iari#682]
I would like to see a breakdown of references based on where they show up in a Wikipedia article.  E.g. Notes, Further reading, External links (or whatever), etc.

**Comment by dpriskorn** [comment]
This requires rewriting the extractor method to return internally a new class MediawikiSection with two attributs: name and references.

**Comment by mojomonger** [comment]
doe sit make sense to return a "mediawikiSection" property in a reference detail?  Reasons for NOT is that a reference may span multiple sections, correct?

**Comment by dpriskorn** [comment]
No. I'm thinking about going the other way and letting general references be a subset of the section they appear in.

Similarly I could move footnote references into the section also and let the section be a locus.

The advantage of this is that we can drill down per section going forward in our metrics.
