### ISSUE TITLE
as a developer I want to gain access to the gpt API to determine link boundaries in PDFs

### ISSUE THREAD

**Issue by dpriskorn** [internetarchive/iari#777]
before sending off data to gpt we should ensure that it would actually improve the output. we can do that by first extracting links before removing lfs and hashing them. then after removing lfs we do the same again. if the total number of links or any of the hashes mismatch we tell gpt to do it better.

**Comment by dpriskorn** [comment]
blocked while awaiting access

**Comment by ibnesayeed** [comment]
Are we extracting links from the annotation layer of PDFs or the text layer? In the case of annotations, it usually a lot simple to extract links, unless the PDF is not formatted well. The latter case can be tricky as line-breaks and hyphenations can be at play.

**Comment by dpriskorn** [comment]
I know nothing about the annotation layer. I'll read up on it and check if PyMuPDF support it

**Comment by dpriskorn** [comment]
Found https://pymupdf.readthedocs.io/en/latest/annot.html

**Comment by dpriskorn** [comment]
See https://github.com/internetarchive/iari/issues/783

**Comment by dpriskorn** [comment]
stalled so closing
