### ISSUE TITLE
Deploying latest version of IARI breaks on launch

### ISSUE THREAD

**Issue by harej** [internetarchive/iari#788]
Deploying the latest IARI main branch (as of writing) results in this:

```
Traceback (most recent call last):
  File "/data/project/check-references/www/python/src/app.py", line 3, in <module>
    from src.models.api import app
ImportError: cannot import name 'app' from 'src.models.api' (./src/models/api/__init__.py)
```

**Comment by dpriskorn** [comment]
What command are you running it with?
`./run-api.sh`?

**Comment by harej** [comment]
I am using `webservice --backend=kubernetes python3.9 start` which I am told does basically the same thing as the gunicorn call in run-api.sh.

**Comment by harej** [comment]
My concern is that it _did_ work before and now it doesn't.

**Comment by dpriskorn** [comment]
Oh interesting. I never ran it on Kubernetes.
I'll try to see if I can replicate it locally

**Comment by dpriskorn** [comment]
I cannot reproduce your issue on my local machine
See https://github.com/internetarchive/iari/issues/789
