### ISSUE TITLE
All /article and /pdf endpoints are returning a 504 (gateway Timeout) error

### ISSUE THREAD

**Issue by mojomonger** [internetarchive/iari#805]
Try:

https://archive.org/services/context/wari/v2/statistics/article?url=https://en.wikipedia.org/wiki/Easter_Island&regex=bibliography|further reading|works cited|sources|external links

or, for a pdf file (https://www.africau.edu/images/default/sample.pdf) that exists:

https://archive.org/services/context/wari/v2/statistics/pdf?url=https://www.africau.edu/images/default/sample.pdf

**Comment by dpriskorn** [comment]
This is not related to the AWS instance which works fine it seems, e.g. http://18.217.22.248/v2/check-url?url=https://www.easterisland.travel and http://18.217.22.248/v2/statistics/pdf?url=https://www.africau.edu/images/default/sample.pdf
