### ISSUE TITLE
as a data consumer I want to analyze any revision of any article in Wikipedias so I can see changes to references over time

### ISSUE THREAD

**Issue by dpriskorn** [internetarchive/iari#807]
this necessitates:
- updating the wari_id to include revision_id in the end

**Comment by dpriskorn** [comment]
@harej is this something you want?

**Comment by harej** [comment]
Yes, but Mark and I both agree it's not a high priority at the moment. The idea is to insert a revision ID and get the response for the revision at that ID.

**Comment by dpriskorn** [comment]
For us to store and serve data of references on past article revisions we need the revision id as input also in references, the easiest way to do that is extending wari id to also include the revision id.

This enables is to store and serve past revisions efficiently and easily and does not require a big rewrite 😀

**Comment by dpriskorn** [comment]
We thus need the url for the article and the revision to get the data we need

Which endpoint return wikitext for a past revision?
https://m.mediawiki.org/wiki/API:REST_API/Reference/Sample_code:Get_revision ?
