### ISSUE TITLE
Have /references endpoint accept article URL

### ISSUE THREAD

**Issue by harej** [internetarchive/iari#819]
Like how I can request `/article` data for a URL:

```
https://archive.org/services/context/iari/v2/statistics/article?url=https://en.wikipedia.org/wiki/Austria&regex=test
```

I would like to be able to do the same thing with the `/references` endpoint, for example:

```
https://archive.org/services/context/iari/v2/statistics/references?url=https://en.wikipedia.org/wiki/Austria&all=true
```

This would be useful if I am working with a list of page titles and not page IDs.

**Comment by dpriskorn** [comment]
Do you want it to support revisions also?

**Comment by dpriskorn** [comment]
I'm guessing you want this to "save" a request, right? In that case this is a very special case I would say. 
This endpoint does no fetching from the internet currently.
It is very simple and just reads from the cache on disk.

**Comment by harej** [comment]
Retrieving data by URLs is not a special case. I want to be able to go from article URL to wikitext references. I don't care what the implementation is. I just want it to happen.

**Comment by harej** [comment]
If this endpoint is only meant to read data that is already cached, then we should revisit the idea of adding original wikitext to the `/article` endpoint.

**Comment by dpriskorn** [comment]
I can do that very easily 😀
I'll keep the references lightweight by removing only the url_objects and the template_objects

**Comment by dpriskorn** [comment]
Closing in favor of https://github.com/internetarchive/iari/issues/831
