### ISSUE TITLE
as a customer/consumer/developer i want to see the debug output from the /pdf endpoint with as many PyMuPdf functions as we can so we can solve PDF link parsing problems

### ISSUE THREAD

**Issue by mojomonger** [internetarchive/iari#857]
PyMuPdf has these functions for extracting content:
```
extractXHTML()
extractXML()
extractHTML()
extractJSON()

extractDICT()
extractBLOCKS()
extractRAWDICT()
extractRAWJSON()
```
We should see an output for each of these functions if the debug=true parameter is set for the /pdf endpoint.

At least the first four extractions should deliver to the debug output.

**Comment by dpriskorn** [comment]
Done in code now.
Note that the json is 188 MB for $ curl "http://127.0.0.1:5000/v2/statistics/pdf?url=https://s3.documentcloud.org/documents/23782225/mwg-fdr-document-04-16-23-1.pdf&refresh=true" -o debug.json

![image](https://github.com/internetarchive/iari/assets/68460690/392c753a-d3c6-4313-aa36-fd1528a28e3a)
@mojomonger how do you want me to wing this? Should I just merge this and then the user will have to wait a long time to download all the json in the browser?
