### ISSUE TITLE
as a customer I want the check-url to support using also the testdeadlink API by default so I can see if it solves the 4xx status code issues reliably

### ISSUE THREAD

**Issue by dpriskorn** [internetarchive/iari#858]
> it appears that the IABot testdeadlinks.php endpoint is working, and it would be good to get that into IARI as soon as we can. Right now i am testing the endpoint with cURL, and discovering how to pass an array of URLs.
I suggest we work on the changing the /check-url endpoint, keeping the default functionality for now and adding a "method=iabot" parameter until things settle down and we know that the iabot method works.

**Comment by mojomonger** [comment]
This is how i accessed the status of 2 urls at once with curl:

```
curl -XPOST https://iabot-api.archive.org/testdeadlink.php \
-d $'urls=https://www.nytimes.com/2009/01/21/opinion/21wed1.html\nhttps://www.realclearpolitics.com/video/2009/02/moran_obama.html' \
-d "authcode=579331d2dc3f96739b7c622ed248a7d3" \
-d "returncodes=1"
```

We will have to re-visit the batch fetching of URLs, especially regarding refresh=true, etc.

**Comment by mojomonger** [comment]
I suggest implementing `/check-url` as a single url case for now.
1. This is simpler than trying to code for an array parameter of urls
2. we have not tried sending large arrays of urls in an endpoint
3. It keeps the code simple for now
4. (CON) it will beat on the IABot server, but for now, thats ok as we are still just testing

We could implement a `/check-urls` endpoint later down the line, after we discuss issues such as:
1. Sending an array of urls along the endpoint
2. Applying timeout on the backend for an array of link checks
3. Possible automatic integration with the /article endpoint (we wouldn't have to pass an array of urls to the endpoint)
