### ISSUE TITLE
As a data consumer i want the errors from IABot testdeadlink endpoint included in the /check-url json data

### ISSUE THREAD

**Issue by mojomonger** [internetarchive/iari#876]
something like this comes from https://iabot-api.archive.org/testdeadlink.php:
```
{
    "results": {
        "https:\/\/orb.binghamton.edu\/cgi\/viewcontent.cgi?article=1041": 400,
        "errors": {
            "https:\/\/orb.binghamton.edu\/cgi\/viewcontent.cgi?article=1041": "RESPONSE CODE: 400"
        }
    },
    "servetime": 1.2438
} 
```
the content of the "errors" field should be added to the /check-url json code, along with the testdeadlink_status_code property

**Comment by dpriskorn** [comment]
Wouldn't it be best to do this in the check-urls endpoint instead?

**Comment by mojomonger** [comment]
we do not yet have the check-urls endpoint yet, do we?

Also, even if we did, we still want the error_text added to the check-url json because that's the way IARE is currently using.
